"""Added Bugs field

Revision ID: 0907edc6ba17
Revises: 48b7c2f4beec
Create Date: 2018-08-21 21:33:47.642544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0907edc6ba17'
down_revision = '48b7c2f4beec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Log', sa.Column('bugs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Log', 'bugs')
    # ### end Alembic commands ###
