"""Added szzType and szzDesc cols to SZZBlame table

Revision ID: 20053d30f7ca
Revises: 88c5cb19a2d4
Create Date: 2018-08-24 15:12:21.917191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20053d30f7ca'
down_revision = '88c5cb19a2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SZZBlame', sa.Column('szzDesc', sa.String(), nullable=True))
    op.add_column('SZZBlame', sa.Column('szzType', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SZZBlame', 'szzType')
    op.drop_column('SZZBlame', 'szzDesc')
    # ### end Alembic commands ###
