"""Added SZZ Log Related Tables

Revision ID: 48b7c2f4beec
Revises: 014faf0389b8
Create Date: 2018-08-17 08:03:45.422513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b7c2f4beec'
down_revision = '014faf0389b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BugPattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patternList', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('repoInfo', sa.String(), nullable=True),
    sa.Column('cloneStartDate', sa.String(), nullable=True),
    sa.Column('cloneFinishDate', sa.String(), nullable=True),
    sa.Column('isPrivate', sa.Integer(), nullable=True),
    sa.Column('repoName', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.String(), nullable=True),
    sa.Column('m', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('repoId', sa.Integer(), nullable=False),
    sa.Column('parents', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('branches', sa.String(), nullable=True),
    sa.Column('files', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('pushdateTimestamp', sa.String(), nullable=True),
    sa.Column('revIndex', sa.Integer(), nullable=True),
    sa.Column('gDump', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repoId'], ['Repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RepoFile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repoId', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('revs', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repoId'], ['Repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BugFix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bugPatternId', sa.Integer(), nullable=False),
    sa.Column('bugs', sa.String(), nullable=True),
    sa.Column('isBugFix', sa.Integer(), nullable=True),
    sa.Column('logId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bugPatternId'], ['BugPattern.id'], ),
    sa.ForeignKeyConstraint(['logId'], ['Log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Repos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Repos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('cloneFinishDate', sa.VARCHAR(), nullable=True),
    sa.Column('cloneStartDate', sa.VARCHAR(), nullable=True),
    sa.Column('isPrivate', sa.INTEGER(), nullable=True),
    sa.Column('repoInfo', sa.VARCHAR(), nullable=True),
    sa.Column('repoName', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('BugFix')
    op.drop_table('RepoFile')
    op.drop_table('Log')
    op.drop_table('Repo')
    op.drop_table('BugPattern')
    # ### end Alembic commands ###
