"""added repoName field

Revision ID: 5a8e9ac5ac7d
Revises: 3df2b373398c
Create Date: 2018-08-07 02:35:23.325194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8e9ac5ac7d'
down_revision = '3df2b373398c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repos', sa.Column('repoName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Repos', 'repoName')
    # ### end Alembic commands ###
