"""Added SZZBlame table

Revision ID: 88c5cb19a2d4
Revises: 496ababc041b
Create Date: 2018-08-24 03:08:51.135839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c5cb19a2d4'
down_revision = '496ababc041b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SZZBlame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repoId', sa.Integer(), nullable=False),
    sa.Column('blames', sa.String(), nullable=True),
    sa.Column('blamesAnalysis', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repoId'], ['Repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SZZBlame')
    # ### end Alembic commands ###
